u-boot: fix compile failure with dtc headers
I was seeing a lot of failures with fdt functions:

| from 1_v2016.07+gitAUTOINC+59428fe010-r0/git/tools/../common/bootm.c:30,
| /usr/include/libfdt.h:1798:19: error: redefinition of 'fdt_appendprop_cell'
|  1798 | static inline int fdt_appendprop_cell(void *fdt, int nodeoffset,

| 1_v2016.07+gitAUTOINC+59428fe010-r0/git/tools/../include/libfdt.h:1535:19:
      note: previous definition of 'fdt_appendprop_cell' was here

facebook/openbmc encountered this problem when trying to upgrade to the
warrior branch of Yocto and a fix was supplied by @aehs29 at:
    https://github.com/facebook/openbmc/pull/105

Ported this patch to meta-aspeed.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I7ed3628a3dd0d587fd886929639e71d14789a25c