u-boot: fix compile failure with dtc headers
I was seeing a lot of failures with fdt functions:

| from 1_v2016.07+gitAUTOINC+59428fe010-r0/git/tools/../common/bootm.c:30,
| /usr/include/libfdt.h:1798:19: error: redefinition of 'fdt_appendprop_cell'
|  1798 | static inline int fdt_appendprop_cell(void *fdt, int nodeoffset,

| 1_v2016.07+gitAUTOINC+59428fe010-r0/git/tools/../include/libfdt.h:1535:19:
      note: previous definition of 'fdt_appendprop_cell' was here

Backported a patch that use to exist in upstream Yocto for u-boot
2016.07, but no longer does since upstream has moved farther along.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I7ed3628a3dd0d587fd886929639e71d14789a25c