aspeed: Add Aspeed SDK recipes for U-boot
Start by copying oe-core recipes-bsp/u-boot/ into the Aspeed BSP.  The
uboot recipes in oe-core master currently point to 2019.07 u-boot and
the Aspeed SDK branch being pointed to by this patch is based on uboot
upstream 2019.04.  There weren't any changes in oe-core going from
2019.04 to 2019.07 so thats OK.

After copying the oe-core recipes, fix up SRC_URI, HOMEPAGE, and a
couple other variables to point at the Aspeed u-boot fork.

The current aspeed-master-v2019.04 tip and evb-ast2600_defconfig will produce
a uboot binary but make returns non-zero:

  CFGCHK  u-boot.cfg
   Error: You must add new CONFIG options using Kconfig
   The following new ad-hoc CONFIG options were detected:
   CONFIG_RAM
   Please add these via Kconfig instead. Find a suitable Kconfig
   file and add a 'config' or 'menuconfig' option.
   make: *** [Makefile:1010: all] Error 1

As such the utility of this recipe is limited until the above issue is
addressed.

Change-Id: I18ac4a5a41052c967101356653fb51d425ac73d8
Signed-off-by: Brad Bishop <bradleyb@fuzziesquirrel.com>